### ISSUE TITLE
Is it actually using GPU?

### ISSUE THREAD

**Issue by daxiongshu** [kopopt/fast_tffm#1]
Hi thank you very much for this great software! When I run the python fast_tffm.py train sample.cfg, I saw there is some GPU usage. So does this fm actually run on GPU despite that README says it is CPU-only?

**Comment by kopopt** [comment]
@daxiongshu That's weird. Actually I developed this software on machines without GPU card, and everything goes well. Moreover, the core operators I implemented in "cc/" folder is cpu version only. Could you please double-check the gpu usage actually comes from fast_tffm? It will be more helpful if you could identify which operators the gpu usage comes from. I will investigate further investigate it. Thanks!

**Comment by kopopt** [comment]
@daxiongshu  FYI, the tensorflow version I installed is "cpu only" version. I haven't run the code on the "gpu" version tensorflow yet. Is it possible that the "gpu" version tensorflow will consume some gpu no matter what mode is chosen?

**Comment by daxiongshu** [comment]
Thank you for the reply! Yeah, it seems CPU does all heavy lifting. The GPU process only uses 64 MB GPU memory. Previously i thought maybe that is due to the small batch size but when i increase batch size 10x the GPU process still uses 64MB. I installed the GPU version tensorflow and the code runs very well. Thank you!

I saw the nested loops in cc/fm_grad_op.cc so yeah it is CPU-like implementation. Do you happen to know where i can find some guides for implementing GPU ops? I'd like to contribute to this repo with a GPU version.

Thank you very much!

**Comment by kopopt** [comment]
Welcome to contribute :) There are numerous operator implementations in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels . You can check how they work.

However, when I print the timeline for each operators, it seems that currently the most time consuming operators is the parse operator; therefore, the gpu implementation might not bring any difference. You can verify that. Thanks.
